// <auto-generated />
namespace BT4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_colum_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_colum_account));
        
        string IMigrationMetadata.Id
        {
            get { return "202110071512089_add_colum_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
